In [1]:
import warnings
warnings.filterwarnings('ignore')

In [11]:
import numpy as np

a = np.array([1, 3, 2])

a

array([1, 3, 2])

In [5]:
a = np.array([[1, 3, 2], [4, 5, 6]], dtype=np.complex128)
a

array([[1.+0.j, 3.+0.j, 2.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [6]:
a = np.array([[1, 3, 2], [4, 5, 600000]], dtype=np.int16)
a

array([[    1,     3,     2],
       [    4,     5, 10176]], dtype=int16)

In [7]:
A = np.array([[3, 4, 5],
             [1, 1, 1,]])

B = np.array([[5, 5, 10],
             [3, 1, 2,]])



In [8]:
A + B

array([[ 8,  9, 15],
       [ 4,  2,  3]])

In [9]:
A = np.array([[3, 4, 5],
             [1, 1, 1,]])

B = np.array([[5, 5, 10],
             [3, 1, 2,],
             [4, 4, 12]])

In [11]:
np.dot(A, B)

array([[47, 39, 98],
       [12, 10, 24]])

In [12]:
A = np.array([[3, 4, 5],
             [1, 1, 1,]])
A.T

array([[3, 1],
       [4, 1],
       [5, 1]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
A = np.array([[5, 5, 10],
             [3, 1, 10,],
             [4, 4, 12]])
np.linalg.inv(A)

array([[ 0.7 ,  0.5 , -1.  ],
       [-0.1 , -0.5 ,  0.5 ],
       [-0.2 ,  0.  ,  0.25]])

In [15]:
X = np.array(
    [
        [23, 0.5, 1],
        [35, 1, 1],
        [18, 0, 1]
    ]
)

Y = np.array([55, 100, 45])


In [17]:
xxt = np.dot(X.T, X)
xxt_inv = np.linalg.inv(xxt)

In [21]:
xxt_inv_xxt = np.dot(xxt_inv, X.T)
final_betas = np.dot(xxt_inv_xxt, Y)

In [22]:
final_betas

array([  5., -30., -45.])

In [2]:
import pandas as pd

X = pd.read_csv('X.csv', encoding='utf8', sep=";").drop(['Предсказание', 'Unnamed: 0'], axis = 1)
Y = pd.read_csv('Y.csv', encoding='utf8', sep=";").drop(['Unnamed: 0'], axis = 1)

In [5]:
X.head()

Категория  Цель в долларах  Срок  Год публикации  Close_brent  CAD  CHF  \
0  6035.989239           1000.0    39            2009        46.05    0    0   
1  3591.033473          80000.0    87            2009        46.05    0    0   
2  3661.424550             20.0     8            2009        46.05    0    0   
3  4321.245721             99.0    79            2009        46.05    0    0   
4  6035.989239           1900.0    28            2009        46.05    0    0   

   DKK  EUR  GBP  ...  Design  Fashion  Film & Video  Food  Journalism  Music  \
0    0    0    0  ...       0        1             0     0           0      0   
1    0    0    0  ...       0        0             1     0           0      0   
2    0    0    0  ...       0        0             0     0           0      0   
3    0    0    0  ...       0        0             0     0           0      0   
4    0    0    0  ...       0        1             0     0           0      0   

   Photography  Publishing  Technology  Theater  
0            0           0           0        0  
1            0           0           0        0  
2            0           0           0        0  
3            0           0           1        0  
4            0           0           0        0  

[5 rows x 32 columns]

In [6]:
Y.head()

target2
0    625.0
1     22.0
2     35.0
3    145.0
4    387.0

In [3]:
from sklearn.linear_model import LinearRegression

# shift + tab - подсказки по функциям
model = LinearRegression()
model.fit(X, Y)

for column, coef in zip(X.columns, model.coef_[0]):
    print(column, coef)

print(model.intercept_)

Категория 0.9917555611549553
Цель в долларах 0.00046052215322221063
Срок 85.5337025015047
Год публикации 865.6289534577179
Close_brent 196.28519379075962
CAD 473.2109778789071
CHF 8884.62227328367
DKK 548.5493235036904
EUR 468.8986749995491
GBP 2799.723380111349
HKD -2027.4214619465286
JPY -8407.156812756733
MXN -3912.5584157550293
NOK -1168.2763539199163
NZD -398.3255261056959
SEK 2115.060009988414
SGD -1306.1393608065212
USD 7031.440729247643
Art -88.1148499172364
Comics -507.19470318294054
Crafts -626.5313243926707
Dance -363.5870362012495
Design -229.8043898194433
Fashion -292.6419253905818
Film & Video -29.220090607057365
Food -717.4180545660636
Journalism -469.19813210091377
Music -274.95703843168656
Photography 222.37988265132915
Publishing -361.4547636853225
Technology -209.00762162294654
Theater 260.1727219898667
[-1760975.79508463]


In [12]:
# пробуем повторить явно расчёт линейной модели
# добавим константу явно
X['constant'] = 1

xxt = np.dot(X.T, X)
xxt_inv = np.linalg.inv(xxt)
xxt_inv_xxt = np.dot(xxt_inv, X.T)
final_betas = np.dot(xxt_inv_xxt, Y)

final_betas

array([[ 9.91755561e-01],
       [ 4.60522153e-04],
       [ 8.55337026e+01],
       [ 8.65628953e+02],
       [ 1.96285197e+02],
       [ 4.73210978e+02],
       [ 8.88462227e+03],
       [ 5.48549324e+02],
       [ 4.68898675e+02],
       [ 2.79972338e+03],
       [-2.02742146e+03],
       [-8.40715681e+03],
       [-3.91255841e+03],
       [-1.16827635e+03],
       [-3.98325526e+02],
       [ 2.11506001e+03],
       [-1.30613936e+03],
       [ 7.03144073e+03],
       [-8.81148499e+01],
       [-5.07194703e+02],
       [-6.26531324e+02],
       [-3.63587036e+02],
       [-2.29804390e+02],
       [-2.92641925e+02],
       [-2.92200907e+01],
       [-7.17418054e+02],
       [-4.69198132e+02],
       [-2.74957038e+02],
       [ 2.22379883e+02],
       [-3.61454764e+02],
       [-2.09007622e+02],
       [ 2.60172722e+02],
       [-1.76097579e+06]])

In [13]:
# на больших матрицах формула работает очень медленно

matrix = np.random.rand(50000, 50000)

In [ ]:
# не запускай это
matrixdot = np.dot(matrix.T, matrix)
matrix_inv = np.linalg.inv(matrixdot)